# Generated by Django 4.2.1 on 2023-05-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.AlterField(
            model_name='person',
            name='nome',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='sobrenome',
            field=models.TextField(),
        ),
    ]
