# Generated by Django 4.2.1 on 2023-05-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_person_email_alter_person_nome_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Perguntas',
        ),
        migrations.RenameField(
            model_name='perguntas',
            old_name='nome',
            new_name='pergunta',
        ),
        migrations.RenameField(
            model_name='perguntas',
            old_name='sobrenome',
            new_name='resposta',
        ),
    ]
