# Generated by Django 4.2.1 on 2023-05-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_respostas_perguntas_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntas',
            name='pergunta',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='perguntas',
            name='resposta',
            field=models.TextField(null=True),
        ),
    ]
