# Generated by Django 4.2.1 on 2023-05-10 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_alter_perguntas_pergunta_alter_perguntas_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntas',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perguntas',
            name='pergunta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perguntas',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
