# Generated by Django 4.2.1 on 2023-05-10 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_perguntas_autor_alter_perguntas_pergunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntas',
            name='resp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perguntas',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
    ]
